plugins {
    id 'com.android.application'
}

android {
    namespace 'cl.andres.ordenafotos'
    compileSdk 35

    defaultConfig {
        applicationId 'cl.andres.ordenafotos'
        minSdk 29
        targetSdk 35
        versionCode 3
        versionName '1.2'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:image-labeling:17.0.9'
    implementation 'com.google.mlkit:text-recognition:16.0.1'
}
